
name: 'Gradle Action'

description: 'Action for Gradle.'

branding:
  icon: 'loader'
  color: 'orange'

inputs:
  command:
    description: 'gradle command.'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
