
name: deploy

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  gradle:
    uses: cc332030/gradle-action/.github/workflows/gradle.yml@master
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
      ORIGIN_PATH: build/libs/boot.jar
      REMOTE_PATH: /home/program/${REPOSITORY_NAME}/boot.jar
      PREPARE_COMMAND: docker stop ${REPOSITORY_NAME}
      ACTION_COMMAND: sh /home/program/${REPOSITORY_NAME}/install.sh
    with:
      command: sh gradlew build
